### ISSUE TITLE
CMake Error: Could not find SDL2

### ISSUE THREAD

**Issue by Nicolas97220** [rockytriton/LLD_gbemu#2]
Hi @rockytriton ,

I tried to follow the steps to build part1 on my windows environment.
Unfortunately, I got a CMake error that indicate that SDL2 is missing:

CMake Error at /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find SDL2 (missing: SDL2_LIBRARY SDL2_INCLUDE_DIR)
Call Stack (most recent call first):
  /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:600 (_FPHSA_FAILURE_MESSAGE)
  cmake/sdl2/FindSDL2.cmake:313 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  CMakeLists.txt:74 (find_package)

However, when I look in /mingw64/lib/ I can see the libSDL2.a and libSDL2.dll.a files
Any idea how to solve this ?

**Comment by Nicolas97220** [comment]
Solution: pacman -S mingw-w64-x86_64-gcc

**Comment by jclever77** [comment]
Hey Nicolas, I was wondering if you did anything different than the video/readme instructions said. I've been having a lot of trouble building this project, but I've followed all the steps exectly.

**Comment by Nicolas97220** [comment]
Yes I managed to build this project by manually linking the libraries. If you can detail your issue I can try to help.

**Comment by jclever77** [comment]
I appreciate it, but luckily I was able to get it to build successfully!
